[mgr]
prepend_keymap = [
  { on = "<C-s>",    run = "plugin kdeconnect-send",            desc = "Send selected files via KDE Connect" },
  { on = ["M", "m"], run = "plugin mount" },
  { on = ["M", "s"], run = "plugin sshfs -- menu",              desc = "Open sshfs menu" },
  { on = ["R", "b"], run = "plugin recycle-bin",                desc = "Open Recycle Bin menu" },
  { on = "u",        run = "plugin restore",                    desc = "Restore last delete files/folders" },
  { on = "y",        run = ["yank", "plugin clipboard -- --action=copy"] },
  { on = "<C-p>",    run = "plugin clipboard -- --action=paste" }
]
