[mgr]
linemode = "size"

[plugin]
  # only put the most used files here, as yazi has a 16 preloader limit
  prepend_preloaders = [
    { mime = "{audio,video,image}/*", run = "mediainfo" },

    # Adobe Illustrator
    { mime = "application/postscript", run = "mediainfo" },
    { mime = "application/illustrator", run = "mediainfo" },
    { mime = "application/vnd.adobe.illustrator", run = "mediainfo" },
  ]

  prepend_previewers = [
    { mime = "{audio,video,image}/*", run = "mediainfo"},
    { mime = "application/subrip", run = "mediainfo" },

    # Adobe Illustrator
    { mime = "application/postscript", run = "mediainfo" },
    { mime = "application/illustrator", run = "mediainfo" },
    { mime = "application/dvb.ait", run = "mediainfo" },
    { mime = "application/vnd.adobe.illustrator", run = "mediainfo" },
    { mime = "image/x-eps", run = "mediainfo" },
    { mime = "application/eps", run = "mediainfo" },
    { url = "*.{ai,eps,ait}", run = "mediainfo" },
  ]
